## **Online Workshop - Big Data Analytics untuk Bisnis**

---
*Modul 2 Dasar - Dasar Bahasa Pemrograman Python*


# **A. Dasar-Dasar Bahasa Pemrograman Python**

Pada tutorial kali ini, kita akan belajar dasar-dasar bahasa pemrograman python. Materi ini akan menjadi bekal bagi pembaca sebelum lebih jauh masuk dalam kegiatan pemrograman menggunakan python. Adapun yang akan dibahas dalam tutorial kali ini, antara lain:

1. Sintaks dasar python
2. Operator dalam python
3. Tipe data python
4. Percabangan dan perulangan
5. Fungsi

## **1 Sintaks Dasar Python**

### *1.1 Statement*

Statement merupakan seluruh perintah yang dieksekusi di python.

In [ ]:
1 + 2

3

### *1.2 Baris dan Indentasi*

Python tidak menggunakan tanda { } untuk menandai blok / grup kode. Blok kode di python menggunakan tanda indentasi (spasi). Jumlah spasi untuk setiap baris yang ada dalam satu blok kode harus sama. Contoh yang benar adalah sebagai berikut:

In [ ]:
nilai = 80

if nilai >= 75:
  print("lulus dengan nilai", nilai)
else:
  print("tidak lulus")

lulus dengan nilai 80


### *1.3 Tanda Kutip* 

Python menggunakan tanda kutip tunggal (‘), ganda (“), maupun triple (”’ atau “””) untuk menandai string, sepanjang stringnya diawali oleh tanda kutip yang sama di awal dan akhir string. 

In [ ]:
print('saya')

saya


In [ ]:
print('my name is "Andi"')

my name is "Andi"


In [ ]:
print("my name is \"Andi\"")

my name is "Andi"


In [ ]:
print("my name is 'Andi'")

my name is 'Andi'


In [ ]:
print("""
Saya suka 
makan bakso
""")


Saya suka 
makan bakso



### *1.4 Variabel*

Di python, variabel tidak perlu dideklarasikan secara eksplisit. Deklarasi atau pembuatan variabel terjadi secara otomatis pada saat kita memberi (menugaskan) suatu nilai ke variabel. Tanda sama dengan ( = ) digunakan untuk memberikan nilai ke variabel.

In [ ]:
a = 1+2
a

3

### *1.5 Tanda Pagar*

Tanda pagar (#) digunakan untuk menandai komentar di python. Komentar tidak akan diproses oleh interpreter Python. Komentar hanya berguna untuk programmer untuk memudahkan memahami maksud dari kode.

In [ ]:
# jumlahkan angka 1 dan 2 dan simpan dalam variabel dgn nama a
a = 1+2
a

3

## **2 Operator**

Operator merupakan simbol atau kata kunci (*keyword*) yang dapat dioperasikan pada sebuah atau beberapa nilai dan melakukan operasi matematika. Contoh: operator `*` digunakan untuk mengalikan dua buah bilangan `x * y`



### *2.1 Operator Matematika*

Operator-operator matematika yang ada di python antara lain:

| Tipe       | Operator  | Deskripsi                    |
|:-----------|:----------|:-----------------------------|
| Unary      | `-`       | menunjukkan bil. positif atau negatif |
| Binary     | `+`, `-`  | penjumlahan dan pengurangan  |
|            | `*`, `/`  | perkalian dan pembagian      |
|            | `%`       | modulo - menghitung sisa pembagian |
|            | `**`      | pemangkatan                  |
|            | `//`      | pembagian integer (tanpa sisa bagi) |

In [ ]:
1 + 2 // 3 ** 2 % 9

1

### *2.2 Operator Perbandingan*

Operator perbandingan atau relasional merupakan operator yang digunakan untuk membandingkan dua buah nilai. 

| Operator |  Deksripsi                                                       |
|:---------|:-----------------------------------------------------------------|
| `==`     | menghasilkan `True` jika kedua nilai sama                        |
| `!=`     | menghasilkan `True` jika kedua nilai tidak sama                  |
| `>`      | menghasilkan `True` jika nilai sebelah kiri lebih besar          |
| `<`      | menghasilkan `True` jika nilai sebelah kiri lebih kecil          |
| $\ge$    | menghasilkan `True` jika nilai sebelah kiri lebih besar atau sama dengan nilai sebelah kanan |
| $\le$    | menghasilkan `True` jika nilai sebelah kiri lebih kecil atau sama dengan nilai sebelah kanan |
  

In [ ]:
x = 2
y = 3

# cek
(x+y) >= (x**2 % y*2)

True

### *2.3 Operator Logik*

Terdapat sejumlah operator logik yang di dukung oleh python, antara lain:

| Operator  | Deskripsi                            |
|:----------|:-------------------------------------|
| `and`     | kedua operand bernilai `True` maka hasilnya `True`|
| `or`      | salah satu operand bernilai `True`  maka hasilnya `True`|
| `not`     | menghasilkan negasi dari kondisi yang disebutkan |

In [ ]:
x = 2
y = 3

# cek
(x+y >= y**2) and not (x < y)

False

## **3 Tipe Data**

Python memilik beberapa tipe data, pada kali ini terdapat enam tipe data yang akan dipelajari, yaitu:
*   Number (Bilangan)
*   String
*   List
*   Tuple
*   Set
*   Dictionary


### *3.1 Number*

Tipe data bilangan yang umum ada 2 yaitu, integer dan float. Integer adalah bilangan bulat, sedangkan float adalah bilangan pecahan (desimal). Selain itu ada tipe bilangan lain, yaitu bilangan kompleks yaitu bilangan yang memiliki bagian real dan imajiner.

In [ ]:
x = 5 
print(x, "tipenya adalah ", type(x))
x = 2.0
print(x, "tipenya adalah ", type(x))
x = 1+2j
print(x, "tipenya adalah ",type(x))

5 tipenya adalah  <class 'int'>
2.0 tipenya adalah  <class 'float'>
(1+2j) tipenya adalah  <class 'complex'>


### *3.2 String*


Satu atau serangkaian karakter yang diletakkan diantara tanda kutip, baik tanda kutip tunggal ( ‘ ) maupun ganda ( ” ). Huruf, angka, maupun karakter lainnya yang digabung menjadi teks adalah contoh string.

String adalah tipe data yang anggotanya berurut dan memiliki indeks. Indeks dimulai dari angka 0 bila dimulai dari depan dan -1 bila diindeks dari belakang. Tiap karakter bisa diakses menggunakan indeksnya dengan formatnamastring[indeks] . Pada string juga bisa dilakukan slicing atau mengakses sekelompok substring dengan format namastring[awal:akhir]. Untuk jelasnya bisa diperhatikan contoh berikut.

In [ ]:
kalimat = "Saya suka Makan"

print(kalimat)      # print string lengkap
print(kalimat[0])   # print karakter pertama
print(kalimat[-1])  # print karakter terakhir
print(kalimat[4:7]) # print dari indeks 4 - 6
print(kalimat[:4])  # print dari indeks 0 - 3

Saya suka Makan
S
n
 su
Saya


### *3.3 List*


tipe data yang berisi item yang berurut. Seperti halnya tipe data string, tiap item (anggota) list memiliki indeks sesuai dengan urutannya. Indeks dimulai dari 0 dan bukan dari 1.

List bisa berisi anggota dengan tipe yang sama maupun berbeda. Untuk mendeklarasikan list, digunakan tanda kurung [ ] dan masing-masing anggotanya dipisahkan oleh tanda koma.

Untuk mengakses item dari list caranya adalah dengan memanggil nama list diikuti indeks dari item yang bersangkutan, yaitu dengan format namalist[index]
Selain itu bisa juga dilakukan pengaksesan terhadap sejumlah item dari indeks ke indeks. Hal ini disebut slicing. Contohnya sebagai berikut:

In [ ]:
x = [5,10,15,20,25,30,35,40]

a = x[2]
b = x[0:3]
c = x[5:]

print (a,b,c, sep="\n")

15
[5, 10, 15]
[30, 35, 40]


In [ ]:
# mengubah nilai elemen 1 dan 5
x[0], x[4] = True, 'Saya'

print(x)

[True, 10, 15, 20, 'Saya', 30, 35, 40]


In [ ]:
# menambahkan elemen baru pada list
x.insert(0, "first")
x.append("last")

print(x)

['first', True, 10, 15, 20, 'Saya', 30, 35, 40, 'last']


In [ ]:
# menghapus list
del x


In [ ]:
print(x)

NameError: ignored

### *3.4 Tuple*

Jenis data lain yang mirip dengan list. Perbedaannya dengan list adalah anggotanya tidak bisa diubah (immutable). List bersifat mutable, sedangkan tuple bersifat immutable. Sekali tuple dibuat, maka isinya tidak bisa dimodifikasi lagi.

In [ ]:
white = (255,255, 255)
red = (255,0,0)
print(white)
print(red[0])
print(red[1])


(255, 255, 255)
255
0


In [ ]:
# tuple bersifat immutable, bila kita run kode ini, akan memunculkan error
red[0] = 128

TypeError: ignored

### *3.5 Set*

Salah satu tipe data di Python yang tidak berurut (unordered).Set memiliki anggota yang unik (tidak ada duplikasi). Jadi misalnya kalau kita meletakkan dua anggota yang sama di dalam set, maka otomatis set akan menghilangkan yang salah satunya.

Set dibuat dengan meletakkan anggota – anggotanya di dalam tanda kurung kurawal { }, dipisahkan menggunakan tanda koma. Kita juga bisa membuat set dari list dengan memasukkan list ke dalam fungsi set()

In [ ]:
# set integer 
my_set = {1,2,3} 
print(my_set)

In [ ]:
# set dengan menggunakan fungsi set() 
my_set = set([1,2,3]) 
print(my_set) 

In [ ]:
# bila kita mengisi duplikasi, set akan menghilangkan salah satu 
my_set = {1,2,2,3,3,3} 
print(my_set) 

### *3.6 Dictionary*

Tipe data yang tiap anggotanya terdiri dari pasangan kunci-nilai (key-value). Mirip dengan kamus dimana ada kata ada arti. Dictionary umumnya dipakai untuk data yang besar dan untuk mengakses anggota data secara acak. Anggota dictionary tidak memiliki indeks.

Dictionary dideklarasikan dengan menggunakan tanda kurung kurawal { }, dimana anggotanya memiliki bentuk kunci:nilai atau key:value dan tiap anggota dipisah tanda koma. Kunci dan nilainya bisa memiliki tipe sembarang.

In [ ]:
d = {'one':'satu', 'two':'dua', 'three':3}
print(d)

{'one': 'satu', 'two': 'dua', 'three': 3}


In [ ]:
#Untuk mengakses nilai dari anggota dictionary, kita menggunakan key-nya.
a = d['one']
b = d['two']

print (a,b)

satu dua


In [ ]:
# menambahkan item
d.update({"four":"empat"})
print(d)

{'one': 'satu', 'two': 'dua', 'three': 3, 'four': 'empat'}


In [ ]:
# menghapus elemen terakhir
d.popitem()

('four', 'empat')

In [ ]:
# mengosongkan isi dictionary
d.clear()

In [ ]:
# menghapus dictionary
del d

## **4 Percabangan dan Perulangan**


### *4.1 Percabangan*


Percabangan mengevaluasi kondisi atau ekspresi yang hasilnya benar atau salah .  Kondisi atau ekspresi tersebut disebut ekspresi boolean. Hasil dari pengecekan kondisi adalah True atau False. Bila benar (True), maka pernyataan yang ada di dalam blok kondisi tersebut akan dieksekusi. Bila salah (False), maka blok pernyataan lain yang dieksekusi.

Terdapat tiga jenis percabangan dalam python, yaitu:
1.   if ...
2.   if ... else ...
1.   if ... elif ... else ...



####**Pernyataan If**
Pernyataan if menguji satu buah kondisi. Bila hasilnya benar maka pernyataan di dalam blok if tersebut dieksekusi. Bila salah, maka pernyataan tidak dieksekusi. Contoh Sintaksnya adalah seperti berikut:

In [ ]:
# Bila bilangan positif, tampilkan pesan

angka = 5
if angka > 0:
    print(angka, "adalah bilangan positif.")

In [ ]:
# yang berikut akan bernilai False sehingga tidak dieksekusi, karena nilai angka tidak lebih dari 0
angka = -1
if angka > 0:
    print(angka, "adalah bilangan positif.")

#### **Pernyataan if ... else**
Pernyataan if…else menguji 2 kondisi. Kondisi pertama kalau benar, dan kondisi kedua kalau salah. Sintaksnya adalah seperti berikut:



In [ ]:
# Program menguji apakah sebuah bilangan positif atau negatif dan menampilkan pesan ke monitor
bilangan = 5
if bilangan >= 0:
    print("Positif atau Nol")
else:
    print("Bilangan negatif")

In [ ]:
# Coba juga mengubah bilangan menjadi bilangan = -1 dan perhatikan hasilnya
bilangan = -1
if bilangan >= 0:
    print("Positif atau Nol")
else:
    print("Bilangan negatif")

#### **Pernyataan if...elif...else**
Pernyataan if…elif…else digunakan untuk menguji lebih dari 2 kondisi. Bila kondisi pada if benar, maka pernyataan di dalamnya yang dieksekusi. Bila salah, maka masuk ke pengujian kondisi elif. Terakhir bila tidak ada if atau elif yang benar, maka yang dijalankan adalah yang di blok else. Sintaksnya adalah seperti berikut:

In [ ]:
# Di sini kita menguji apakah sebuah bilangan adalah bilangan positif, nol, atau negatif dan menampilkan hasilnya ke layar
bilangan = 5.5
if bilangan > 0:
    print("Bilangan positif")
elif bilangan == 0:
    print("Nol")
else:
    print("Bilangan negatif")

In [ ]:
# Coba juga mengganti bilangan jadi bilangan = 0
bilangan = 0
if bilangan > 0:
    print("Bilangan positif")
elif bilangan == 0:
    print("Nol")
else:
    print("Bilangan negatif")

In [ ]:
# Coba juga mengganti bilangan jadi bilangan = -5.5
bilangan = -5.5
if bilangan > 0:
    print("Bilangan positif")
elif bilangan == 0:
    print("Nol")
else:
    print("Bilangan negatif")

### *4.2 Perulangan*


Python mengeksekusi program baris perbaris. Mulai dari baris satu, dua, dan seterusnya. Ada kalanya, kita perlu mengeksekusi satu baris atau satu blok kode program beberapa kali. Hal ini disebut dengan perulangan atau biasa disebut looping atau iterasi.

Di python, perulangan bisa dilakukan dengan dua cara atau metode, yaitu:

1. Menggunakan for
2. Menggunakan while

#### **Perulangan dengan for**
Perulangan dengan for memiliki tambahan variabel. Variabel  digunakan untuk penampung sementara nilai dari sequence pada saat terjadi perulangan. Sequence adalah tipe data berurut seperti string, list, dan tuple.

Perulangan terjadi sampai looping mencapai elemen atau anggota terakhir dari sequence. Bila loop sudah sampai ke elemen terakhir dari sequence, maka program akan keluar dari looping.

contoh perulangan for adalah sebagai berikut

In [ ]:
# Program untuk menemukan jumlah bilangan dalam satu list

# List number
numbers = [7, 5, 9, 8, 4, 2, 6, 4, 1]

# variablel untuk menyimpan jumlah
sum = 0

# iterasi
for each in numbers:
    sum = sum + each

# Output
print("Jumlah semuanya:", sum)

In [ ]:
#Fungsi Range
mapel = ['matematika', 'fisika', 'kimia']

# iterasi list menggunakan indeks
for i in range(len(mapel)):
    print("Saya suka", mapel[i])

#### **Perulangan Menggunakan While**
Perulangan menggunakan while akan menjalankan blok pernyataan terus menerus selama kondisi bernilai benar.

While juga memiliki input dengan nama expression. Expression merupakan ekspresi atau kondisi apa saja, dan untuk nilai selain nol dianggap True. Iterasi akan terus berlanjut selama kondisi benar. Bila kondisi salah, maka program akan keluar dari while dan lanjut ke baris pernyataan di luar while.

In [ ]:
count = 0
while (count < 5):
    print('The count is:', count)
    count = count + 1
print('Good bye!')

Di sini, blok pernyataan print('The count is:', count), dijalankan terus selama count masih lebih kecil dari 5. Count ditambah 1 setiap kali iterasi. Pada saat nilai count mencapai 5, maka kondisi menjadi False dan program keluar dari looping while dan melanjutkan baris selanjutnya yaitu print("Good bye").

#### **Kendall Looping**
Looping umumnya akan berhenti bila kondisi sudah bernilai salah. Akan tetapi, seringkali kita perlu keluar dari looping di tengah jalan tergantung keperluan. Hal ini bisa kita lakukan dengan menggunakan kata kunci break dan continue.

Statement break memaksa program keluar dari blok looping di tengah jalan. Sedangkan statement continue menyebabkan program langsung melanjut ke step / interval berikutnya dan mengabaikan (skip) baris kode di bawahnya (yang satu blok). Jelasnya perhatikan contoh berikut:

In [ ]:
# contoh penggunaan statement break
for letter in "Programming":
    if letter == "g":
        break
    print("Huruf sekarang:", letter)
print("Good bye")

In [ ]:
#Bila pada program di atas kita ganti kode break menjadi continue, maka hasilnya akan jadi seperti berikut:
for letter in "Programming":
    if letter == "g":
        continue
    print("Huruf sekarang:", letter)
print("Good bye")

#### **Pernyataan While else**
Python mendukung penggunaan else sebagai pasangan dari while. Blok pernyataan else hanya akan dieksekusi bila kondisi while bernilai salah. Contohnya adalah sebagai berikut


In [ ]:
count = 0
while (count < 5):
    print(count, "kurang dari 5")
    count = count + 1
else:
    print(count, "tidak kurang dari 5")

## **5 Fungsi**


Fungsi adalah grup/blok program untuk melakukan tugas tertentu yang berulang. Fungsi membuat kode program menjadi reusable, artinya hanya di definisikan sekali saja, dan kemudian bisa digunakan berulang kali dari tempat lain di dalam program.


Fungsi memecah keseluruhan program menjadi bagian – bagian yang lebih kecil . Dengan semakin besarnya program, maka fungsi akan membuatnya menjadi lebih mudah diorganisir dan dimanage.

Sejauh ini, kita sudah menggunakan beberapa fungsi, misalnya fungsi print(), type(), dan sebagainya. Fungsi tersebut adalah fungsi bawaan dari Python. Kita bisa membuat fungsi kita sendiri sesuai kebutuhan.

Contoh pemakaian fungsi adalah sebagai berikut:

In [ ]:
def sapa(nama): 
    """Fungsi ini untuk menyapa seseorang sesuai nama yang dimasukkan sebagai parameter""" 
    print("Hi, " + nama + ". Apa kabar?") 

# pemanggilan fungsi 
sapa('Umar') 

### *5.1 Argumen Kata Kunci*


Argumen dengan kata kunci berkaitan dengan cara pemanggilan fungsi. Ketika menggunakan argumen dengan kata kunci, fungsi pemanggil menentukan argumen dari nama parameternya. Hal ini membuat kita bisa mengabaikan argumen atau menempatkannya dengan sembarang urutan.

Python dapat menggunakan kata kunci yang disediakan untuk mencocokkan nilai sesuai dengan parameternya. Jelasnya ada pada contoh berikut:

In [ ]:
# Definisi fungsi 
def print_info( nama, usia ): 
    """Fungsi ini menampilkan info yang dimasukkan"""
    print ("Nama: ", nama) 
    print ("Usia: ", usia) 

# Memanggil fungsi 
# output 
print_info( 25, "Budi" )

### *5.2 Argumen Default*


Fungsi dengan argumen default menggunakan nilai default untuk argumen yang tidak diberikan nilainya pada saat pemanggilan fungsi. Pada contoh berikut, fungsi akan menampilkan usia default bila argumen usia tidak diberikan:

In [ ]:
# Definisi fungsi 
def print_info( nama, usia= 17 ): 
    """Fungsi ini menampilkan info yang dimasukkan""" 
    print ("Nama: ", nama) 
    print ("Usia ", usia) 

# Pemanggilan fungsi tidak menyediakan argumen usia 
print_info( nama = "Galih" ) 

Nama:  Galih
Usia  17


5.3 Fungsi dengan Return Value

Fungsi yang telah kita buat sebelumnya merupakan sebuah fungsi yang mencetak informasi melalui argumen yang diberikan. Fungsi tersebut hanya memeberikan *side effect* berupa nilai yang tercetak, namun tidak merubah *environment* (tidak ada nilai yang dapat disimpan). Sebagai contoh jalankan fungsi sebelumnya dan simpan ke dalam sebua variabel dengan nama `info`.

In [ ]:
info = print_info( nama = "Galih" )

Nama:  Galih
Usia  17


Cetak variabel tersebut dan lihat apakah terdapat nilai yang tercetak ?

In [ ]:
print(info)

None


Fungsi tersebut tidak mencetak nilai apapun, dalam hal ini tidak terdapat nilai yang tersimpan dalam variabel tersebut. Untuk membuat fungsi tersebut dapat menyimpan sebuah nilai, kita dapat menggunakan keyword `return` pada akhir fungsi.

In [ ]:
# Definisi fungsi 
def print_info( nama, usia= 17 ): 
    """Fungsi ini menampilkan info yang dimasukkan""" 
    print ("Nama: ", nama) 
    print ("Usia ", usia) 

    return [nama, usia]

In [ ]:
info = print_info("Andi")

Nama:  Andi
Usia  17


In [ ]:
# cetak nilai dalam variabel
print(info)

['Andi', 17]


# **B. Dasar-Dasar Modul Pandas**

![](https://hackernoon.com/hn-images/0*Xhz01Vby2rg86xZj)





Pada tutorial kali ini, kita akan belajar dasar-dasar modul pandas. Padas merupakan sebuah modul python yang dapat kita gunakan untuk melakukan manipulasi data.

Adapun yang akan diperlajari dalam tutorial ini, antara lain:

1. Dataframe
2. *Import* data
3. Menggabungkan data
4. *Reshaping* dan *Pivoting*
5. Transformasi data
7. Aggregasi data
8. *Export* data

Untuk cara instalasi modul pandas, jalankan perintah berikut:

In [ ]:
!pip3 install pandas
!pip3 install numpy
!pip install psycopg2

Untuk memuat modulnya jalankan sintaks berikut:

In [ ]:
import pandas as pd
import numpy as np

## **1 Dataframe**






Dataframe merupakan struktur data seperti sebuah tabel atau *spreadsheet*. Dataframe dapat pula dikatakan sebagai sebuah koleksi dari baris dan kolom, dimana tiap kolom dapat memiliki sebuah jenis data yang dapat berbeda dengan jenis data kolom lainnya. Struktur sebuah dataframe ditampilkan dalam gambar berikut:

![](https://www.w3resource.com/w3r_images/pandas-data-structure.svg)

### *1.1 Membuat Dataframe*

Terdapat berbagai macam cara untuk membuat sebuah dataframe. Cara yang paling umum digunakan adalah dengan membentuk sebuah objek dictionary (*keys and values obejct*) dengan panjang *values* yang sama. Cara lainnya adalah dengan menggunakan Numpy arrays dengan panjang yang sama.


In [ ]:
data = {'kota': ['Surabaya','Surabaya','Surabaya', 'Jakarta','Jakarta'],
        'tahun': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 2, 2.3, 5, 5.3]}

frame = pd.DataFrame(data)

In [ ]:
# cek dataframe
frame

kota  tahun  pop
0  Surabaya   2000  1.5
1  Surabaya   2001  2.0
2  Surabaya   2002  2.3
3   Jakarta   2001  5.0
4   Jakarta   2002  5.3

Dataframe dapat pula dibuat dengan menyuplai dictionary dan nama kolom yang diinginkan pada dataframe tersebut. Selain itu, kita dapat pula menambahkan index yang dapat berfungsi sebagai pembeda pada tiap baris data.

In [ ]:
frame2 = pd.DataFrame(data, columns= ['kota', 'tahun', 'pop'],
                      index= ['satu', 'dua', 'tiga', 'empat', 'lima'])

In [ ]:
frame2

kota  tahun  pop
satu   Surabaya   2000  1.5
dua    Surabaya   2001  2.0
tiga   Surabaya   2002  2.3
empat   Jakarta   2001  5.0
lima    Jakarta   2002  5.3

### *1.2 Subset Dataframe*

Terkadang kita hanya tertarik melakukan analisis pada sebagian data yang kita inginkan. Untuk melakukannya, kita seringkali hanya mengambil sebagian kolom atau baris dari data. Untuk itu, kita perlu belajar melakukan proses subset pada dataframe.

#### **Subset Kolom**

![](https://pandas.pydata.org/docs/_images/03_subset_columns.svg)

In [ ]:
# ambil kolom nama kota
frame2['kota']

satu     Surabaya
dua      Surabaya
tiga     Surabaya
empat     Jakarta
lima      Jakarta
Name: kota, dtype: object

In [ ]:
# atau
frame2.kota

satu     Surabaya
dua      Surabaya
tiga     Surabaya
empat     Jakarta
lima      Jakarta
Name: kota, dtype: object

In [ ]:
# ambil kolom tahun dan populasi
frame2[["tahun","pop"]]

tahun  pop
satu    2000  1.5
dua     2001  2.0
tiga    2002  2.3
empat   2001  5.0
lima    2002  5.3

In [ ]:
# ambil kolom dengan indeks ke-0
frame2.iloc[:,0]


satu     Surabaya
dua      Surabaya
tiga     Surabaya
empat     Jakarta
lima      Jakarta
Name: kota, dtype: object

#### **Subset Baris**

![](https://pandas.pydata.org/docs/_images/03_subset_rows.svg)

In [ ]:
# filter baris dengan kota Surabaya
frame2[frame2['kota']=="Surabaya"]

kota  tahun  pop
satu  Surabaya   2000  1.5
dua   Surabaya   2001  2.0
tiga  Surabaya   2002  2.3

In [ ]:
# filter baris ke 0-3
frame2.iloc[0:4,:]

kota  tahun  pop
satu   Surabaya   2000  1.5
dua    Surabaya   2001  2.0
tiga   Surabaya   2002  2.3
empat   Jakarta   2001  5.0

#### **Subset Baris dan Kolom**

![](https://pandas.pydata.org/docs/_images/03_subset_columns_rows1.svg)

In [ ]:
# filter kolom kota dan pop dengan pop >= 5
frame2.loc[frame2['pop']>= 5, ['kota', 'pop']]

kota  pop
empat  Jakarta  5.0
lima   Jakarta  5.3

### *1.3 Menambahkan Kolom*

![](https://pandas.pydata.org/docs/_images/05_newcolumn_1.svg)

In [ ]:
# menambahkan kolom jawa_timur
is_jawatimur = ['TRUE', 'TRUE', 'TRUE', 'FALSE', 'FALSE']

frame2['jawa_timur'] = is_jawatimur
frame2

kota  tahun  pop jawa_timur
satu   Surabaya   2000  1.5       TRUE
dua    Surabaya   2001  2.0       TRUE
tiga   Surabaya   2002  2.3       TRUE
empat   Jakarta   2001  5.0      FALSE
lima    Jakarta   2002  5.3      FALSE

## **2 Import Data**




### *2.1 Membaca File Text*

Pandas memiliki sejumlah fungsi yang dapat kita gunakan untuk membaca file text dalam berbagai ekstensi. Fungsi-fungsi yang dapat kita gunakan adalah sebagai berikut:

| Fungsi       | Deskripsi                    |
|:-------------|:-----------------------------|
| `read_csv`   | membaca file, url, atau objek yang menggunakan koma sebagai pemisah datanya|
| `read_table` | membaca file, url, atau objek yang menggunakan tab (`\t`) sebagai pemisah datanya|
| `read_fwf` | membaca data dengan format *fixed-width column* |
| `read_clipboard` | versi lain dari `read_table` yang dapat digunakan untuk membaca data dari *clipboard*. Berguna untuk mengkonversi tabel yang ada pada sebuah halaman web |

Dataset yang akan dibaca dalam tutorial kali ini adalah dataset `Stackoverflow`. Dataset ini telah dibagi ke dalam 3 buah file yang akan membantu kita nantinya untuk memahami proses *join* dan *merging* data pada tahapan berikutnya. Dataset yang digunakan memiliki 5594 baris dan 21 kolom. Untuk informasi lebih lanjut, pembaca dapat mengunjungi tautan [berikut](https://insights.stackoverflow.com/survey/).

In [ ]:
data1 = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/stackoverflow_left.csv")
data2 = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/stackoverflow_right.csv")
data3 = pd.read_csv("/content/drive/My Drive/Colab Notebooks/dataset/stackoverflow_bottom.csv")

FileNotFoundError: ignored

Untuk mengecek 5 observasi teratas pada masing-masing data, gunakan *method* `head`.

In [ ]:
data3.head()

Untuk mengecek 5 observasi terbawah, gunakan method `tail`

In [ ]:
data3.tail()

NameError: ignored

Lebih jauh kita dapat mengecek struktur data pada dataframe menggunakan method `info`.

In [ ]:
data3.info()

NameError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


Untuk melihat ringkasan data numerik pada masing-masing kolom, jalankan method `describe`.

In [ ]:
data3.describe()

NameError: ignored

### *2.2 Membaca File JSON*

JSON (*JavaScript Object Notation*) merupakan format standard pengiriman data oleh HTTP *request* antara web browser dengan aplikasi lainnya. Format atau file JSON akan kita temui saat kita berinteraksi dengan API. Struktur JSON mirip dengan dictionary yang ada pada python dengan key dan value yang saling berpasangan yang mewakili tiap baris dalam sebuah tabel data.

Untuk memulai latihan, pertama-tama kita akan membuat file sebuah file JSON yang akan kita baca.

In [ ]:
import json

# index type orientation
obj1 = """
{"0":{"Product":"Desktop Computer","Price":700},
"1":{"Product":"Tablet","Price":250},
"2":{"Product":"iPhone","Price":800},
"3":{"Product":"Laptop","Price":1200}}
"""

# value orientation
obj2 = """
[["Desktop Computer",700],
["Tablet",250],
["iPhone",800],
["Laptop",1200]]
"""

# column orientation
obj3 = """
{"Product":{"0":"Desktop Computer","1":"Tablet","2":"iPhone","3":"Laptop"},
"Price":{"0":700,"1":250,"2":800,"3":1200}}
"""

Untuk memuat sebuah objek JSON  ke dalam python, gunakan fungsi `loads`.

In [ ]:
result = json.loads(obj3)
result

{'Price': {'0': 700, '1': 250, '2': 800, '3': 1200},
 'Product': {'0': 'Desktop Computer',
  '1': 'Tablet',
  '2': 'iPhone',
  '3': 'Laptop'}}

Untuk mengkonversi objek `result` menjadi dataframe, jalankan sintaks berikut:

In [ ]:
data_json1 = pd.DataFrame(result)
data_json1

Product  Price
0  Desktop Computer    700
1            Tablet    250
2            iPhone    800
3            Laptop   1200

Kita dapat langsung membaca file JSON tanpa perlu menggunakan fungsi `load`. Pandas menyediakan fungsi `read_json` untuk membaca file JSON. Argumen tambahan yang diperlukan adalah menspesifikasikan lokasi file json yang hendak dibaca

In [ ]:
data_json1 = pd.read_json(obj1, orient="index")
data_json1

Product  Price
0  Desktop Computer    700
1            Tablet    250
2            iPhone    800
3            Laptop   1200

Kita akan mencoba menggunakan object JSON yang lebih rumit dibanding sebelumnya. Pada contoh kali ini, kita akan coba membaca dataset USDA Food Database.

Kita akan coba membaca object tersebut dan melihat output yang dihasilkan.

In [ ]:
result = json.load(open("/content/drive/My Drive/Colab Notebooks/dataset/database.json"))
result[0]

NameError: ignored

In [ ]:
data = pd.DataFrame(result)

NameError: ignored

In [ ]:
data

Product  Price
0  Desktop Computer    700
1            Tablet    250
2            iPhone    800
3            Laptop   1200

Berdasarkan output yang dihasilkan, terdapat *nested value* pada kolom ke-0. Untuk mengatasi hal tersebut, kita perlu melakukan normalisasi dataframe tersebut.

In [ ]:
portion = pd.json_normalize(result, record_path="portions", meta = ["id",	"description",	"tags",	"manufacturer",	"group"	], record_prefix="portions_")
portion

KeyError: ignored

In [ ]:
nutrient = pd.json_normalize(result, record_path="nutrients", meta = ["id",	"description",	"tags",	"manufacturer",	"group"	], record_prefix="nutrient_")
nutrient

KeyError: ignored

### *2.3 Membaca Data dari Database Relasional*

Salah satu sumber data yang akan sering ditemui adalah database. Database terbagi atas dua jenis, yaitu: database relasional dan database non-relasional.

Pada materi kali ini, kita akan belajar cara membaca data dari database relasional. Langkah pertama yang perlu dilakukan adalah membuat tabel database relasional.

In [ ]:
import sqlite3

# membuat tabel
query = """
CREATE TABLE test
(provinsi VARCHAR(20), kota VARCHAR(20),
populasi REAL, luas INTEGER
);"""

# membangun koneksi
con = sqlite3.connect(':memory:')
con.execute(query)
con.commit()

Selanjutnya kita perlu mengisi nilai pada tabel yang telah dibuat.

In [ ]:
data = [('Jawa Barat', 'Bandung', 3.1, 2),
        ('Jawa Timur', 'Surabaya', 4.1, 3),
        ('Jakarta', 'Jakarta', 6, 3)]
query = "INSERT INTO test VALUES(?, ?, ?, ?)"

con.executemany(query, data)
con.commit()

Kita dapat menggunakan fungsi `DataFrame` untuk melakukan query pada database yang telah dibuat dan mengembalikan outputnya ke dalam bentuk dataframe.

In [ ]:
# melakukan query data
query = """
SELECT * FROM test
"""
cursor = con.execute(query)

data_sql = pd.DataFrame(cursor.fetchall(), columns=["provinsi", "kota", "pop", "area"])

In [ ]:
data_sql

provinsi      kota  pop  area
0  Jawa Barat   Bandung  3.1     2
1  Jawa Timur  Surabaya  4.1     3
2     Jakarta   Jakarta  6.0     3
3  Jawa Barat   Bandung  3.1     2
4  Jawa Timur  Surabaya  4.1     3
5     Jakarta   Jakarta  6.0     3

Cara lain yang dapat digunakan adalah dengan menggunakan fungsi `read_frame` dari pandas.

In [ ]:
pd.read_sql_query(query, con)

provinsi      kota  populasi  luas
0  Jawa Barat   Bandung       3.1     2
1  Jawa Timur  Surabaya       4.1     3
2     Jakarta   Jakarta       6.0     3
3  Jawa Barat   Bandung       3.1     2
4  Jawa Timur  Surabaya       4.1     3
5     Jakarta   Jakarta       6.0     3

In [ ]:
# menutup koneksi
con.close()

#### **SQLite Database**

Setelah kita belajar mengambil data dari database yang telah kita buat sendiri, sekarang kita akan belajar cara untuk mengambil data dari sebuah file. Langkah pertama yang perlu dilakukan adalah membangun koneksi dengan database.

In [ ]:
# membangun koneksi
con = sqlite3.connect('/content/drive/My Drive/Colab Notebooks/dataset/chinook.db')

OperationalError: ignored

Skema relasi objek database relasional digambarkan sebagai berikut:

![](https://cdn.sqlitetutorial.net/wp-content/uploads/2015/11/sqlite-sample-database-color-768x386.jpg)

Untuk mengecek tabel yang tersedia dalam database, jalankan perintah berikut:

In [ ]:
# cek nama tabel tersedia
query = """
SELECT name FROM sqlite_master WHERE type='table'
"""
cursor = con.execute(query)

# cetak nama tabel
print(cursor.fetchall())

ProgrammingError: ignored

Sekarang, kita akan mencoba untuk melakukan query untuk nama album yang dikelurakan oleh masing-masing artis. Untuk melakukannya, kita perlu mengambil dua buah tabel, yaitu: `artists` dan `albums` dan menggabungkan dua tabel tersebut.

In [ ]:
# melakukan query data
query = """
SELECT artists.Name, albums.Title 
FROM artists 
INNER JOIN albums
ON artists.ArtistId = albums.ArtistId
"""
cursor = con.execute(query)

pd.read_sql_query(query, con)

ProgrammingError: ignored

In [ ]:
# menutup koneksi
con.close()

#### **PostgreSQL Database**

Sebelumnya kita telah belajar mengambil data dari sebuah file database, sekarang kita akan belajar mengambil data dari sebuah server database. Kali ini, kita akan menggunakan sebuah modul, yaitu: SQLAlchemy untuk terhubung ke server.

Secara umum untuk tersambung ke  database menggunakan  modul SQLAlchemy, kita perlu membuat engine menggunakan format berikut:

```
dialect+driver://username:password@host:port/database
```

**Keterangan**:
* Dialect : DBMS yang akan digunakan. DBMS yang tersedia, antara lain:
  + mysql 
  + postgresql
  + oracle
  + firebird
  + microsoft sql server
* Driver : driver yang digunakan sesuai dengan DBMS yang dipilih. Daftar driver yang tersedia ditampilkan pada tabel berikut:

| Database               | DBAPI Driver                                      |
|:-----------------------|:--------------------------------------------------|
| MySQL                  | PyMySQL, MySQL-Connector, CyMySQL, MySQL-Python (default)|
| PostgreSQL             | psycopg2 (default), pg8000, |
| Microsoft SQL Server   | PyODBC (default), pymssql |
| Oracle                 | cx-Oracle (default) |
| Firebird               | fdb (default), kinterbasdb   |


Berikut adalah perintah yang digunakan untuk terhubung ke server:

In [ ]:
from sqlalchemy import  create_engine

engine = create_engine("postgresql+psycopg2://technaut:technaut@latihan.cys7x9qalyhl.ap-northeast-2.rds.amazonaws.com/postgres")
con = engine.connect()

print(con)

Database yang akan kita gunakan adalah database `dvdrental`. Skema ER dari database relasional ditampilkan pada gambar berikut:

![](https://sp.postgresqltutorial.com/wp-content/uploads/2018/03/dvd-rental-sample-database-diagram.png)

Untuk mengecek tabel yang tersedia dalam database, jalankan perintah berikut:

In [ ]:
table_names = engine.table_names()
print(table_names)

['actor', 'store', 'address', 'category', 'city', 'country', 'customer', 'film_actor', 'film_category', 'inventory', 'language', 'rental', 'staff', 'payment', 'film']


Berikut adalah contoh cara melakukan query dan menyimpannya ke dalam dataframe.

In [ ]:
query = """
SELECT LHS.customer_id AS customer_id, LHS.store_id AS store_id, LHS.first_name AS first_name, 
  LHS.last_name AS last_name, LHS.email AS email, LHS.address_id AS address_id, 
  RHS.address AS address, RHS.address2 AS address2
FROM customer AS LHS
LEFT JOIN address AS RHS
ON (LHS.address_id = RHS.address_id)
"""

df = pd.read_sql_query(query, engine)
df

customer_id  store_id  ...                   address address2
0            524         1  ...   1003 Qinhuangdao Street         
1              1         1  ...            1913 Hanoi Way         
2              2         1  ...          1121 Loja Avenue         
3              3         1  ...         692 Joliet Street         
4              4         2  ...          1566 Inegl Manor         
..           ...       ...  ...                       ...      ...
594          595         1  ...       844 Bucuresti Place         
595          596         1  ...  1101 Bucuresti Boulevard         
596          597         1  ...    1103 Quilmes Boulevard         
597          598         1  ...       1331 Usak Boulevard         
598          599         2  ...      1325 Fukuyama Street         

[599 rows x 8 columns]

In [ ]:
con.close()

## **3 Menggabungkan Data**

Dalam melakukan analisis data, kita seringkali memerlukan data dari sumber lain untuk memperkaya hasil analisis data kita. Untuk itu, pada bagian ini kita akan belajar menggabungkan data dari sumber yang berbeda.

### *3.1 Merging*

Fungsi `merge` dapat digunakan untuk melakukan *column join* berdasarkan kolom kunci dari kedua data. Macam-macam proses join yang  dapat dilakukan divisualisasikan dalam gambar berikut:

![](https://lh3.googleusercontent.com/proxy/EtaMOGviUBb15H1GBshCyI5qrDJUMecc_y9vpE8ZThpho4GQqEln91Yqqekw_3KrC2ZLlCudzNdZ4bj4MWyR5G0YMoaMruRvbPX7JF1iQ2a-1ZOs3HhGBwUmdc1iAN7v-uhPP2Oc2ocmGNBcULPv1kpP--8ElR1SI3yqBg)

Argumen dari fungsi `merge` yang akan kita gunakan diringkas dalam tabel berikut;

| Argumen       | Deskrpsi                                             |
|:--------------|:-----------------------------------------------------|
| left          | dataframe yang akan digabungkan pada sebelah kiri    |
| right         | dataframe yang akan digabungkan pada sebelah kanan   |
| how           | tipe join yang digunakan 'inner', 'outer', 'left', dan 'right' |
| on            | nama kolom yang menjadi kolom kunci join. Kolom harus sama-sama dimiliki oleh dua buah tabel dengan nama yang sama |
| left_on       | kolom sebelah kiri yang digunakan sebagai kolom kunci|
| right_on      | kolom sebelah kana yang digunakan sebagai kolom kunci|
| left_index    | menggunakan indeks tabel kiri sebagai kunci join     |
| right_index   | menggunakan indeks tabel kanan sebagai kunci join    |
| sort          | mengurutkan data yang telah digabungkan secara *lexicograph* berdasarkan kolom kunci|




Berikut adalah contoh *left join* `data1` dan `data2`:

In [ ]:
join = pd.merge(data1, data2,
                how='left', on='ID')

join.head()

NameError: ignored

Proses tersebut divisualisasikan pada gambar di bawah ini:

![](https://pandas.pydata.org/docs/_images/08_merge_left.svg)

### *3.2 Concatenating*

Berbeda dengan proses *merging* atau *joining*, *concatenanting* menambahkan baris data berdasarkan data baru yang memiliki nama kolom yang sama. Ini berguna untuk menggabungkan data yang diukur secara periodik. *Concatenating* dilakukan menggunakan fungsi `concat`. Visualisasi proses ini ditampilkan dalam gambar berikut:

![](https://pandas.pydata.org/docs/_images/08_concat_row1.svg)


Pada contoh berikut, kita akan belajar melakukan *concatenating* menggunakan dataset `join` (dataset hasil join) dan dataset `data3`.



In [ ]:
full_data = pd.concat([join, data3])

full_data.head()

NameError: ignored

## **4 Reshaping dan Pivoting**

Pada bagian ini kita akan belajar melakukan proses *reshaping* dan *pivoting* dataframe.

### *4.1 Reshaping*

Terdapat dua buah method yang akan dibahas pada sub bahasan ini, antara lain:

* `stack` : operasi ini akan merotasi atau melakukan pivot terhadap kolom sehingga menjadi baris.
* `unstack` : operasi ini adalah kebalikan dari operasi `stack`

In [ ]:
# membuat dataset sederhana
data = pd.DataFrame({'one' : [0,1],
      'two' : [2,3],
      'three' : [4,5]},
    index=pd.Index(['Ohio', 'Colorado'], name='state'))
data

one  two  three
state                    
Ohio        0    2      4
Colorado    1    3      5

In [ ]:
# stack
result = data.stack()
result

state          
Ohio      one      0
          two      2
          three    4
Colorado  one      1
          two      3
          three    5
dtype: int64

In [ ]:
# unstack
result.unstack()

one  two  three
state                    
Ohio        0    2      4
Colorado    1    3      5

### *4.2 Pivoting*

Terdapat dua buah jenis pivot yang akan dipelajari dalam sub bahasan kali ini, antara lain:

* *pivot long* : merubah dataframe *wide format* menjadi *long format* (jumlah kolom lebih sedikit, namun jumlah baris lebih besar)
* *pivot_wide* : kebalikan dari *pivot long*


#### **Pivot Long**

![](https://pandas.pydata.org/docs/_images/07_melt1.svg)

In [ ]:
pv_long = full_data.melt(id_vars=full_data.iloc[:,0:9], var_name="Job")
pv_long

NameError: ignored

#### **Pivot Wide**

![](https://pandas.pydata.org/docs/_images/07_pivot.svg)

In [ ]:
pv_wide = pv_long.pivot(index = 'ID', 
              columns='Job',
              values = 'value')
pv_wide

NameError: ignored

## **5 Transformasi Data**

Pada materi ini, kita akan belajar untuk melakukan transformasi pada dataframe yang telah kita miliki. Transformasi yang akan dipelajari meliputi:

1. Membuang duplikasi data
2. Diskretisasi dan binning
3. Deteksi dan melakukan filter outlier

### *5.1 Membuang Duplikasi Data*

Untuk mengecek apakah pada dataframe terdapat duplikasi data, kita dapat menggunakan method `duplicated`

In [ ]:
# cek duplikat
pv_long.iloc[:,:9].duplicated()

NameError: ignored

Untuk membuang duplikat tersebut, kita dapat menggunakan method `drop_duplicates`.

In [ ]:
# membuang dupliksi data
pv_wide2 = pv_long.iloc[:,:9].drop_duplicates()

# melakukan merging data
pd.merge(pv_wide2, pv_wide, how = "left", on = "ID")

### *5.2 Diskretisasi dan Binning*

Diskretisasi merupakan sebuah proses mengelompokkan data kontinu ke dalam sejumlah bin untuk dianalisa lebih lanjut. Misalkan kita ingin membuat variabel baru yang mengklasifikasikan perusahaan berdasarkan jumlah karyawannya. Berikut adalah sintaks yang digunakan:

In [ ]:
# membuat bin
bin = [0, 500, 1000, 15000]
# membuat label
label = ['kecil', 'sedang', 'besar']
# diskretisasi variabel
pd.cut(full_data['CompanySizeNumber'], bin, labels = label)

Binning dalam proses diskretisasi dapat pula menggunakan pengelompokan berdasarkan jumlah kuantil yang kita spesifikasikan.

In [ ]:
pd.qcut(full_data['CompanySizeNumber'],3, labels=label)

### *5.3 Deteksi dan Melakukan Filter Outlier*

Melakukan filter terhadap nilai outlier merupakan aktivitas yang akan sering kita temui saat kita akan melakukan analisis data. Filter oulier akan dapat membantu kita dalam meningkatkan akuras sebuah model atau guna memenuhi asumsi dalam uji statistik.

In [ ]:
# ambil kolom salary
salary = full_data['Salary']

salary.describe()

In [ ]:
salary.plot.box()

In [ ]:
# filter salary > 175000
salary[salary>175000].plot.box()

## **6 Aggregasi Data**

Agggregasi data merupakan tahapan memecah data menjadi beberapa grup, melakukan operasi pada tiap grup, dan menggabungkan hasil yang telah diperoleh. Aggregasi data dapat pula disebut sebagai operasi *split*, *apply*, dan *combine* yang merujuk dari ketiga proses yang terjadi. Secara visual, aggregasi data dapat dilihat melalui visualisasi berikut:

![](https://pandas.pydata.org/docs/_images/06_groupby1.svg)

In [ ]:
# menghitung nilai median salary tiap negara
grouped = full_data.groupby('Country', as_index=False)
grouped['Salary'].mean()

Untuk menambahkan kolom ringkasan lainnya, kita dapat menggunakan method `agg`

In [ ]:
grouped['Salary'].agg(['mean', 'std', 'median'])

Fungsi statistika lainnya yang dapat digunakan utnuk melakukan aggregasi antara lain:

| Fungsi        | Deskripsi                                    |
|:--------------|:---------------------------------------------|
| count         | jumlah baris tanpa missing value pada kolom  |
| sum           | jumlah nilai sebuah kolom                    |
| median        | nilai median sebuah kolom                    |
| std, var      | simpangan baku dan varians                   |
| min, max      | nilai minimum dan maksimum kolom             |
| prod          | nilai produk dari kolom                      |
| first, last   | nilai pertama dan terakhir sebuah kolom      |

## **7 Eksport Data**

Data yang telah melalui proses pembersihan dapat disimpan ke dalam format `csv` untuk dapat digunakan kembali.

In [ ]:
full_data.to_csv("stackoverflow.csv")

## **8. Referensi**

Untuk memperdalam pemahaman pembaca, silahkan mempelajari tautan berikut:

1. [Dokumentasi Pandas](https://pandas.pydata.org/docs/getting_started/intro_tutorials/01_table_oriented.html#min-tut-01-tableoriented)
2. [Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)

# **C. Dasar-Dasar Modul Numpy**

![](https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png)

Numpy (*Numerical Python*) merupakan paket atau modul yang diperlukan dalam komputasi saintifik berperforma tinggi dan analisis data. Numpy merupakan sebuah dasar dalam penyusunan modul berlevel tinggi yang ada di python. Pada tutorial kali ini kita akan belajar:

1. Numpy ndarray
2. Fungsi matematika universal untuk array
3. Pemrosesan data menggunakan array

Untuk menginstall numpy, jalankan perintah berikut:

In [ ]:
!pip3 install numpy

Untuk mengaktifkan modul terinstall, jalankan perintah berikut:

In [ ]:
import numpy as np

## **1 Numpy ndarray**

Salah satu fitur kunci dari numpy adalah *N-dimensional array object* atau `ndarray`, dimana ia merupakan kontainer yang cepat dan fleksbel untuk menangani dataset besar yang ada di python. Arrray memungkinkan kita untuk melakukan operasi matematika pada seluruh blok data menggunakan sintaks operasi yang mirip atau setara antar elemen skalar.

Sebuah `ndarray` merupakan kontainer multidimensi umum untuk data yang homogen yang berarti jenis data dalam kontainer haruslah sejenis. Setiap array memiliki bentuk (`shape`), sebuah tuple yang mengidentifikasikan dimensi array dan `dtype` yang mendeksripsikan jenis data sebuah array.

### *1.1 Membuat ndarray*

Cara termudah untuk membuat sebuah array adalah dengan menggunakan fungsi `array`. Fungsi ini menerima sejumlah *sequence-like object* dan menghasilkan array yang berisikan data yang telah diinputkan sebelumnya.

In [ ]:
# simple array
data1 = [1, 1, 4, 5, 6, 8]
arr1 = np.array(data1)
arr1

array([1, 1, 4, 5, 6, 8])

Untuk mengecek dimensi array, gunakan method `ndim` atau `shape`.

In [ ]:
arr1.ndim

1

In [ ]:
arr1.shape

(6,)

Untuk cek jenis data yang ada di dalam array, gunakan method `dtype`.

In [ ]:
arr1.dtype

dtype('int64')

Selain fungsi `array`, terdapat fungsi lain yang dapat digunakana  untuk membentuk array. Sebagai contoh `zeros` dan `ones`, meruapak sebuah fungsi untuk membentuk array dengan elemen berupa angka nol dan satu. Argumen tambahan yang diberikan berupa dimensi dari array yang ingin dibentuk.

In [ ]:
# array 2 baris dan 3 kolom
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# array dengan 10 elemen
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Fungsi-fungsi lain yang dapat digunakan untuk membuat sebuah array dirangkum dalam tabel berikut:

| Fungsi        | Deksripsi                                                |
|:--------------|:---------------------------------------------------------|
| array         | mengkonversi data input (list, tuple, array, atau tipe deret angka lainnya) menjadi ndarray |
| asarray       | mengkonversi data input menjadi array tanpa mengcopy data yang dihasilkan jika data input adalah array|
| arrange       | seperti fungsi `arrange` yang telah ada di python, namun menghasilkan array dan bukan list |
| ones, ones_like | memproduksi sebuah array dnegan seluruh elemen berupa angka 1 dengan `shape` dan `dtype` yang diberikan. |
|               | `ones_like` mengambil input array lainnya dan mengkonversinya menjadi array dengan elemen 1 tanpa mengubah dimensi dan jenis data di dalamnya|
| zeros, zeros_like | seperti fungsi `ones` tapi menghasilkan array dengan nilai elemen 0 |
| empty, empty_like | membuat array dengan mengalokasikan memori baru, tapi tidak mengisi array yang terbentuk dengan angka nol atau satu |
|eye, identity | membuat sebuah N x N matriks identitas persegi    |

### *1.2 Jenis Data ndarray*

Jenis data merupakan sebuah objek spesial yang berisikan informasi yang diperlukan oleh ndarray untuk menginterpretasikan sebuah *chunk memory* sebagai bagian dari  jenis data tertentu.

In [ ]:
arr2 = np.array([1,2,3], dtype=np.float64)
arr2.dtype

dtype('float64')

Dtypes adalah bagian dari apa yang membuat NumPy begitu kuat dan fleksibel. Dalam kebanyakan kasus, numpy memetakan langsung ke representasi mesin yang mendasari, yang membuatnya mudah untuk membaca dan menulis aliran data biner disk dan juga untuk menyambung ke kode yang ditulis dalam bahasa tingkat rendah seperti C atau Fortran. Dtypes numerik diberi nama dengan cara yang sama: nama tipe, seperti float atau int, diikuti dengan angka yang menunjukkan jumlah bit per elemen. Nilai floating point presisi ganda standar (apa yang digunakan di balik objek float Python) membutuhkan 8 byte atau 64 bit. Jadi, tipe ini dikenal di NumPy sebagai float64. Untuk melihat daftar lengkap dari jenis data yang didukung oleh numpy, perhatikan tabel berikut:



| Tipe           | Kode Tipe       | Deskripsi                                 |
|:---------------|:----------------|:------------------------------------------|
| int8, uint8    | i1, u1          | Signed dan unsigned 8-bit (1 byte) integer types|
| int16, uint16  | i2, u2          | Signed dan unsigned 16-bit integer types  |
| int32, uint32  | i4, u4          | Signed dan unsigned 32-bit integer types  |
| int64, uint64  | i8, u8          | Signed dan unsigned 32-bit integer types  |
| float16        | f2              | Half-precision floating point             |
| float32        | f4 atau f       | Standard single-precision floating point  Kompatibel dengan C float                 |
| float64, float128 | f8 atau d    | Standard double-precision floating point. Kompatibel dengan C double dan Python float object |
| float128      | f16 atau g       | Extended-precision floating point         |
| complex64, complex128, complex256 | c8, c16, c32 | Bilangan kompleks yang direpresentasikan oleh dua 32, 64, atau 128 float|
| bool          | ?                 | Nilai boolean                            |
| object        | 0                 | Python object type                       |
| string_       | S                 | String                                   |
| unicode_      | U                 | Unicode                                  |


Dengan menggunakan panduan tabel tersebut, kita dapat melakukan modifikasi jenis data pada array yang telah kita buat.

In [ ]:
arr2 = arr2.astype(np.int64)
arr2.dtype

dtype('int64')

### *1.3 Operasi antara Array dan Scalar*

Array merupakan sebuah objek yang penting, sebab array memungkinkan kita melakukan operasi pada data tanpa menuliskan `for` loop. Operasi ini biasanya dinamai operasi tervektorisasi. Setiap operasi aritmatik antara array dengan ukuran elemen yang sama akan dilakukan secara *elementwise*. 

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])

# hitung invers masing-masing elemen
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [ ]:
arr - 1/arr

array([[0.        , 1.5       , 2.66666667],
       [3.75      , 4.8       , 5.83333333]])

### *1.4 Subset Array*

Proses pengindeksan pada array secara prinsip akan berbeda berdasarkan dimensi yang dimiliki array tersebut.

In [ ]:
# subset array satu dimensi
arr1[:3]

array([1, 1, 4])

In [ ]:
# subset array 2 dimensi
arr[1,[0,2]]

array([4., 6.])

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:

# subset array 3 dimensi
arr3d[1,:][1,:]

array([10, 11, 12])

## **2 Fungsi Matematika Universal pada Array**

Fungsi universal (*ufunc*) merupakan sebuah fungsi yang melakukan operasi secara *elementwise* terhadap ndarray. Kita dapat membayangkannya sebagai sebuah fungsi tervektorisasi yang mengambil sebuah input berupa satu atau beberapa nilai skalar dan menghasilkan satu atau beberapa nilai skalar.

Terdapat dua macam fungsi universal yang akan umum digunakan, yaitu:
1. **unary** : menerima input sebuah array
2. **binary** : menerima input dua buah array 

Berikut adalah ringkasan fungsi universal unary yang bisa digunakan:

| Fungsi              | Deskripsi                                   |
|:--------------------|:--------------------------------------------|
| abs, fabs           | menghitung nilai absolut array numerik. Gunakan fabs sebagai alternatif komputasi yang lebih cepat untuk *non-complex-valued data*|
| sqrt                | menghitung nilai akar kuadrat bilangan. Setara dengan array ** 0,5  |
| square              | menghitung kuadrat bilangan. Setara dengan array ** 2 |
| exp                 | menghitung nilai eksponen dari $e^x$ |
| log, log10, log2, log1p | menghitung nilai log natural (basis e), log basis 10, log basis 2 dan log basis (1+x) |
| sign                | menghitung *sign* masing-masing elemen: 1 (positif), 0 (nol), dan -1 (negatif) |
| ceil                | melakukan pembulatan ke atas                |
| floor               | melakukan pembulatan ke bawah               |
| rint                | membulatkan nilai ke integer terdekat dengan tetap mempertahankan tipe data array |
| modf                |Ubah bagian pecahan dan integral dari array sebagai array terpisah |
| isnan               | menghasilkan nilai boolean yang mengidentifikasikan apakah elemen array merupakan missing value atau bukan |
| isfinite, isinf     | menghasilkan nilai boolean yang mengidentifikasikan apakah elemen array merupakan bilangan finit atau bukan, dan sebaliknya |
| cos, cosh, sin, sinh, tan, tanh | fungsi trigonometri biasa dan hiperbolik |
| arccos, arccosh, arcsin, arcsinh, arctan, arctanh | fungsi inverse trigonometri |
| logical_not         | menghitung nilai sebenarnya dari bukan (*not*) x |  

In [ ]:
# sampel array
arr1 = np.arange(10)
arr2 = arr1 * 3

In [ ]:
# akar kuadrat
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# sign
np.sign(arr2)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])

Berikut adalah ringkasan dari fungsi binary:

| Fungsi          | Deskripsi                                                  |
|:----------------|:-----------------------------------------------------------|
| add             | menjumlahkan elemen array                                  |
| substract       | mengurangkan nilai elemen array pertama dengan array kedua |
| multiply        | operasi perkalian elemen array                             |
| divide, floor_divide | operasi pembagian                                     |
| power           | operasi pemangkatan array pertama terhadap array kedua     |
| maximum, fmax   | membandingkan dan mencari nilai maksimum antar dua elemen  |
| minimum, fmin   | membandingkan dan mencari nilai minimum antar dua elemen   |
| mod             | *element-wise modulus*                                     |
| copysign        | melakukan copy sign nilai argumen kedua ke argumen pertama |
| greater, greater_equal, less, less_equal, equal, not_equal | melakukan perbandingan  elemen array pertama dengan kedua |
| logical_and, logical_or, logical_xor | melakukan operasi logik               |

In [ ]:
np.maximum(arr1,arr2)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.divide(arr2, arr1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

## **3 Pemrosesan Data Menggunakan Array**

Menggunakan array NumPy memungkinkan kita untuk mengekspresikan berbagai jenis tugas pemrosesan data sebagai ekspresi array yang ringkas yang mungkin memerlukan loop penulisan. Praktik mengganti loop eksplisit dengan ekspresi array ini biasanya disebut sebagai vektorisasi. Secara umum, operasi array vektorisasi sering kali satu atau dua (atau lebih) lipat lebih cepat daripada padanan Python murni mereka, dengan dampak terbesar dalam jenis perhitungan numerik.

### *3.1 Mengekspresikan Logika Bersyarat sebagai Operasi Array*

Fungsi `where` merupakan bentuk tervektorisasi dari ekspresi `x if condition else y`. Misalkan kita memiliki array dengan elemen boolean dan dua buah array numerik:

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

Misalkan kita ingin mengambil nilai dari `xarr` setiap nilai dalam `cond` adalah `True` dan sebaliknya ambil nilai pada `yarr`. Penulisan loop untuk kondisi tersebut adalah sebagai berikut:

In [ ]:
result = [(x if c else y) 
        for x, y, c in zip(xarr, yarr, cond)]

result

[1.1, 2.2, 1.3, 1.4, 2.5]

Bentuk tervektorisasinya adalah sebagai berikut:

In [ ]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

### *3.2 Metode Matematik dan Statistik*

Serangkaian fungsi matematika yang menghitung statistik tentang seluruh array atau tentang data di sepanjang sumbu dapat diakses menggunakan array method. Agregasi (sering disebut reduksi) seperti sum, mean, dan standar deviasi dapat digunakan dengan memanggil metode instance array atau menggunakan fungsi NumPy:

In [ ]:
arr = np.random.randn(5, 4)
arr.mean()

0.22830916575101073

Contoh lainnya adalah sebagai berikut:

In [ ]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr.cumsum(axis = 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [ ]:
arr.mean(axis = 1)

array([1., 4., 7.])

Fungsi dasar metode statistik yang dapat digunakan pada array dirangkum pada tabel berikut:

| Method        | Deskripsi                               |
|:--------------|:----------------------------------------|
| sum           | jumlah seluruh elemen array atau sepanjang axis |
| mean          | mean aritmatik array                    |
| std, var      | simpangan dan varians                   |
| min, max      | nilai minimum dan maksimum              |
| argmin, agrmax| indeks minimum dan maksimum elemen      |
| cumsum        | jumlah kumulatif elemen                 |
| cumprod       | produk kumulatif elemen                 |

## **4 Referensi**

Jika pembaca ingin mempelajari modul Numpy lebih lanjut, gunakan referensi pada tautan berikut:

1. [Tutorial Numpy](https://numpy.org/learn/)
2. [Numpy Cheat Sheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)